import type { PipelineQuestion, PipelineCategory } from "@/types/fym";

export const PIPELINE_CATEGORIES: PipelineCategory[] = [
  { key: "market", label: "Market Signal", maxScore: 20 },
  { key: "revenue", label: "Revenue Potential", maxScore: 20 },
  { key: "build", label: "Build Feasibility", maxScore: 20 },
  { key: "invisibility", label: "Invisibility Fit", maxScore: 20 },
  { key: "moat", label: "Competitive Moat", maxScore: 20 },
];

export const PIPELINE_QUESTIONS: PipelineQuestion[] = [
  // ── Category 1: Market Signal (Max 20pts) ──
  {
    id: "market_1",
    category: "market",
    categoryLabel: "Market Signal",
    text: "Can you find 10+ people actively complaining about this problem on Reddit, Twitter, or forums?",
    hint: "Real demand shows up as real frustration. If nobody is complaining, nobody will pay to fix it.",
    yesScore: 5,
    impact: "Critical",
    positiveImplication: "Strong demand signal — real people are actively seeking a solution.",
    negativeImplication: "No visible demand. You may be solving a problem nobody has.",
  },
  {
    id: "market_2",
    category: "market",
    categoryLabel: "Market Signal",
    text: "Are people currently paying for an inferior or manual workaround?",
    hint: "Willingness to pay for a bad solution proves willingness to pay for a good one. Free alternatives with no paid workarounds signal weak demand.",
    yesScore: 4,
    impact: "Critical",
    positiveImplication: "Proven willingness to pay — customers already spend money on this problem.",
    negativeImplication: "No existing paid solutions. Monetization will require educating the market.",
  },
  {
    id: "market_3",
    category: "market",
    categoryLabel: "Market Signal",
    text: "Can you describe the target customer in one sentence (job title, pain, context)?",
    hint: "Vague targets like 'small businesses' mean you haven't found real demand. Specificity like 'freelance bookkeepers who waste 3 hrs/week on receipt matching' is signal.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Clear customer avatar — you know exactly who to sell to.",
    negativeImplication: "Vague target audience. Marketing and messaging will be unfocused.",
  },
  {
    id: "market_4",
    category: "market",
    categoryLabel: "Market Signal",
    text: "Is the market growing or at least stable (not shrinking)?",
    hint: "Building in a dying market means fighting headwinds. Check Google Trends for the problem keyword over the past 2 years.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Growing or stable market — tailwinds will help your growth.",
    negativeImplication: "Declining market. You'll fight for a shrinking pie.",
  },
  {
    id: "market_5",
    category: "market",
    categoryLabel: "Market Signal",
    text: "Can you reach 100 potential customers within 48 hours using free channels?",
    hint: "If you can't get in front of prospects quickly (subreddits, Facebook groups, Slack communities, cold DMs), paid acquisition will eat your margins.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Easy distribution — you can reach prospects without spending money.",
    negativeImplication: "Hard to reach customers cheaply. Customer acquisition cost will be high.",
  },
  {
    id: "market_6",
    category: "market",
    categoryLabel: "Market Signal",
    text: "Does this problem recur regularly (weekly/monthly) rather than being a one-time need?",
    hint: "Recurring problems support recurring revenue. One-time problems yield one-time purchases with high churn.",
    yesScore: 2,
    impact: "Nice-to-have",
    positiveImplication: "Recurring pain supports a subscription model with low churn.",
    negativeImplication: "One-time need. You'll constantly need new customers to replace churned ones.",
  },

  // ── Category 2: Revenue Potential (Max 20pts) ──
  {
    id: "revenue_1",
    category: "revenue",
    categoryLabel: "Revenue Potential",
    text: "Can this idea generate at least $500/mo within 90 days of launch?",
    hint: "If reaching $500 MRR takes more than 3 months, the feedback loop is too slow for a side project. You need fast revenue to stay motivated.",
    yesScore: 5,
    impact: "Critical",
    positiveImplication: "Fast path to revenue — you'll see results before losing motivation.",
    negativeImplication: "Slow revenue ramp. Risk of burnout before reaching meaningful income.",
  },
  {
    id: "revenue_2",
    category: "revenue",
    categoryLabel: "Revenue Potential",
    text: "Is there a clear path to $5K+/mo without adding more of your time?",
    hint: "Scalability matters. If doubling revenue requires doubling your hours, you're building a job, not a business. Look for software leverage.",
    yesScore: 4,
    impact: "Critical",
    positiveImplication: "Scalable model — revenue can grow without proportional time investment.",
    negativeImplication: "Linear scaling. More revenue = more hours. This becomes a second job.",
  },
  {
    id: "revenue_3",
    category: "revenue",
    categoryLabel: "Revenue Potential",
    text: "Can you charge $29+/mo (or $99+ one-time) without heavy objections?",
    hint: "Low pricing ($5-9/mo) requires massive volume. At $29+ you need fewer customers to reach freedom numbers. If the problem isn't painful enough for $29, reconsider.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Strong pricing power — fewer customers needed to hit your FYM target.",
    negativeImplication: "Low willingness to pay. You'll need high volume to reach meaningful revenue.",
  },
  {
    id: "revenue_4",
    category: "revenue",
    categoryLabel: "Revenue Potential",
    text: "Is the monetization model simple (subscription, one-time, usage) with no complex billing?",
    hint: "Complex billing (metered, tiered enterprise, multi-party marketplaces) slows you down. Simple SaaS or one-time is best for weekend builds.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Simple billing — Stripe/LemonSqueezy handles everything out of the box.",
    negativeImplication: "Complex billing logic. You'll spend weekends on invoicing instead of features.",
  },
  {
    id: "revenue_5",
    category: "revenue",
    categoryLabel: "Revenue Potential",
    text: "Can you accept payment through Stripe/Gumroad/LemonSqueezy under your LLC (not your name)?",
    hint: "You need to collect money invisibly. Ensure the payment processor shows your LLC name, not your personal name, on customer receipts.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Invisible payments — your LLC name appears on receipts, not yours.",
    negativeImplication: "Payment exposure risk. Your name may appear on customer bank statements.",
  },
  {
    id: "revenue_6",
    category: "revenue",
    categoryLabel: "Revenue Potential",
    text: "Are existing competitors priced high enough that you can undercut profitably?",
    hint: "If competitors charge $99/mo and you can deliver 80% of the value at $29/mo, you have a pricing wedge. If everything is free, monetization is hard.",
    yesScore: 2,
    impact: "Nice-to-have",
    positiveImplication: "Pricing wedge available — you can undercut incumbents and still profit.",
    negativeImplication: "Race to the bottom. Free or cheap competitors make monetization difficult.",
  },

  // ── Category 3: Build Feasibility (Max 20pts) ──
  {
    id: "build_1",
    category: "build",
    categoryLabel: "Build Feasibility",
    text: "Can you build an MVP in one weekend (2 days) using tools you already know?",
    hint: "Scope is the startup killer. If the MVP requires learning a new framework or takes weeks, you'll lose momentum before getting your first customer.",
    yesScore: 5,
    impact: "Critical",
    positiveImplication: "Fast to build — you can have something live by Sunday night.",
    negativeImplication: "Scope too large. You'll lose weeks before shipping anything.",
  },
  {
    id: "build_2",
    category: "build",
    categoryLabel: "Build Feasibility",
    text: "Does the MVP require only 1-2 core features (not a full platform)?",
    hint: "The best MVPs do one thing well. If you need auth + billing + dashboards + integrations + AI before launch, scope is too big.",
    yesScore: 4,
    impact: "Critical",
    positiveImplication: "Focused MVP — one killer feature, not a feature factory.",
    negativeImplication: "Platform play. Too many features required before launch.",
  },
  {
    id: "build_3",
    category: "build",
    categoryLabel: "Build Feasibility",
    text: "Can you use no-code/low-code tools (Cursor, Bolt, v0, Supabase, Vercel) for 80%+ of the build?",
    hint: "Modern tools let you ship in hours, not weeks. If your idea requires custom ML models, native apps, or hardware, it's likely too complex for a side project.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Leveraging modern tools — ship in hours, not weeks.",
    negativeImplication: "Custom tech required. Build time will be 10x longer than expected.",
  },
  {
    id: "build_4",
    category: "build",
    categoryLabel: "Build Feasibility",
    text: "Is deployment straightforward (Vercel, Netlify, Railway) with no complex infrastructure?",
    hint: "If you need Kubernetes, custom servers, or complex CI/CD pipelines, operational overhead will eat your evenings. Deploy in one click or skip it.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "One-click deploy — no DevOps headaches eating your evenings.",
    negativeImplication: "Complex infrastructure. You'll spend more time on ops than product.",
  },
  {
    id: "build_5",
    category: "build",
    categoryLabel: "Build Feasibility",
    text: "Can you handle support alone with under 1 hour/week once launched?",
    hint: "If every customer requires onboarding calls or hand-holding, support becomes a second job. Self-serve products with good docs scale your time.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Self-serve product — minimal support burden after launch.",
    negativeImplication: "High-touch support needed. Each customer costs you time.",
  },
  {
    id: "build_6",
    category: "build",
    categoryLabel: "Build Feasibility",
    text: "Does the idea avoid regulatory hurdles (HIPAA, PCI, GDPR-heavy, fintech compliance)?",
    hint: "Regulated industries add months of compliance work. Unless you already have domain expertise, avoid healthcare data, financial transactions, or children's products.",
    yesScore: 2,
    impact: "Nice-to-have",
    positiveImplication: "No regulatory burden — ship fast without compliance overhead.",
    negativeImplication: "Regulatory minefield. Compliance requirements could delay launch by months.",
  },

  // ── Category 4: Invisibility Fit (Max 20pts) ──
  {
    id: "invisibility_1",
    category: "invisibility",
    categoryLabel: "Invisibility Fit",
    text: "Can you run this business with zero personal branding (no face, no real name)?",
    hint: "If the business requires you to be a public thought leader, do podcasts, or attend events, your employer will find out. Brand-led businesses are not invisible.",
    yesScore: 5,
    impact: "Critical",
    positiveImplication: "Fully anonymous operation — no personal brand exposure needed.",
    negativeImplication: "Personal branding required. Your employer or colleagues will discover this.",
  },
  {
    id: "invisibility_2",
    category: "invisibility",
    categoryLabel: "Invisibility Fit",
    text: "Does this operate in a different industry/niche than your employer?",
    hint: "Even without non-competes, operating in the same space as your day job creates legal risk and increases the chance a colleague discovers your venture.",
    yesScore: 4,
    impact: "Critical",
    positiveImplication: "Clear industry separation — minimal legal risk from your employer.",
    negativeImplication: "Same industry as your employer. High risk of discovery and legal conflict.",
  },
  {
    id: "invisibility_3",
    category: "invisibility",
    categoryLabel: "Invisibility Fit",
    text: "Can all customer interactions happen asynchronously (email, chat, docs)?",
    hint: "Synchronous calls with customers risk schedule conflicts with your day job and leave voice/video recordings that could identify you.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Async-first — no calls to juggle around your day job.",
    negativeImplication: "Sync calls needed. Schedule conflicts and identity exposure risk.",
  },
  {
    id: "invisibility_4",
    category: "invisibility",
    categoryLabel: "Invisibility Fit",
    text: "Can you automate delivery so the product runs 24/7 without you?",
    hint: "If you must be online during business hours to fulfill orders, your day job performance will suffer and colleagues may notice your distraction.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Automated delivery — the product works while you're in meetings.",
    negativeImplication: "Manual fulfillment required. Your day job will suffer.",
  },
  {
    id: "invisibility_5",
    category: "invisibility",
    categoryLabel: "Invisibility Fit",
    text: "Is there zero need for a physical presence (office, warehouse, meetups)?",
    hint: "Physical locations create paper trails (leases, permits) and increase the chance of being seen by someone you know. Pure digital is pure invisible.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "100% digital — no physical footprint to trace back to you.",
    negativeImplication: "Physical presence needed. Paper trails and chance encounters increase exposure.",
  },
  {
    id: "invisibility_6",
    category: "invisibility",
    categoryLabel: "Invisibility Fit",
    text: "Can your LLC own all assets (domain, accounts, IP) with no personal name exposure?",
    hint: "Check that every account (hosting, domain, SaaS tools, app store) can be registered under your LLC. Some platforms require personal identity verification.",
    yesScore: 2,
    impact: "Nice-to-have",
    positiveImplication: "Full LLC ownership — every asset is behind the corporate veil.",
    negativeImplication: "Some platforms require personal identity. Partial name exposure possible.",
  },

  // ── Category 5: Competitive Moat (Max 20pts) ──
  {
    id: "moat_1",
    category: "moat",
    categoryLabel: "Competitive Moat",
    text: "Do existing solutions leave a clear gap you can fill (feature, price, niche)?",
    hint: "If incumbents already do everything well and cheaply, there's no gap to exploit. The best moats start with underserved niches the big players ignore.",
    yesScore: 5,
    impact: "Critical",
    positiveImplication: "Clear market gap — incumbents are missing something obvious.",
    negativeImplication: "No visible gap. Incumbents already serve this market well.",
  },
  {
    id: "moat_2",
    category: "moat",
    categoryLabel: "Competitive Moat",
    text: "Can you build a data or network advantage over time?",
    hint: "User-generated data, integrations, or community effects create compounding moats. Pure commodity tools get cloned overnight.",
    yesScore: 4,
    impact: "Critical",
    positiveImplication: "Compounding advantage — gets stronger with every user.",
    negativeImplication: "Commodity product. Can be cloned by anyone in a weekend.",
  },
  {
    id: "moat_3",
    category: "moat",
    categoryLabel: "Competitive Moat",
    text: "Is the market too small or niche for big companies to bother competing?",
    hint: "Markets under $10M TAM are invisible to venture-backed companies. That's perfect for a micro-SaaS earning $5-20K/mo. Be the big fish in a small pond.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Niche market — too small for big players, perfect for micro-SaaS.",
    negativeImplication: "Large visible market. Expect well-funded competitors to move in.",
  },
  {
    id: "moat_4",
    category: "moat",
    categoryLabel: "Competitive Moat",
    text: "Can you create meaningful switching costs (data lock-in, workflow integration, templates)?",
    hint: "If customers can switch to a competitor in 5 minutes, they will. Integrations, stored data, and custom workflows make switching painful.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "High switching costs — customers stay because leaving is painful.",
    negativeImplication: "Easy to switch away. You'll compete on price alone.",
  },
  {
    id: "moat_5",
    category: "moat",
    categoryLabel: "Competitive Moat",
    text: "Can you ship faster than competitors because of your unique domain expertise?",
    hint: "Your day job knowledge (without using proprietary info) gives you insight competitors lack. This speed advantage compounds with each release.",
    yesScore: 3,
    impact: "Important",
    positiveImplication: "Domain expertise advantage — you ship faster because you understand the problem deeply.",
    negativeImplication: "No unique insight. Competitors can match your features easily.",
  },
  {
    id: "moat_6",
    category: "moat",
    categoryLabel: "Competitive Moat",
    text: "Is there an organic distribution channel (SEO, marketplace, community) you can leverage?",
    hint: "Paid acquisition is expensive and unpredictable. If you can rank for long-tail keywords, list on a marketplace, or tap a community, growth is cheaper.",
    yesScore: 2,
    impact: "Nice-to-have",
    positiveImplication: "Organic distribution — free traffic from SEO, marketplaces, or communities.",
    negativeImplication: "No organic channels. You'll rely on paid ads or manual outreach.",
  },
];
