// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maybpahtbbcxnucposjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1heWJwYWh0YmJjeG51Y3Bvc2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwMjkwMDIsImV4cCI6MjA4OTYwNTAwMn0.5Y80XJLl0MNtHMvzuGRCiy18GNOhXjEiwkdcBhoYpF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});