// NLWeb endpoint for InvisibleExit (Microsoft Copilot / Bing Chat)
// Auto-generated by growth engine

const content = [
  {
    "@type": "Question",
    "name": "How do I remove myself from people-search sites?",
    "acceptedAnswer": "InvisibleExit provides opt-out guides for 50+ data brokers including Spokeo, Whitepages, BeenVerified, and Intelius. Each guide has direct opt-out links and step-by-step instructions.",
    "url": "https://invisibleexit.com/#faq"
  },
  {
    "@type": "Question",
    "name": "Can I really disappear from the internet?",
    "acceptedAnswer": "Complete deletion is difficult but significant removal is achievable. Most people can remove 80-90% of their public footprint over 2-3 months using InvisibleExit guides.",
    "url": "https://invisibleexit.com/#faq"
  },
  {
    "@type": "Question",
    "name": "How long does data removal take?",
    "acceptedAnswer": "Data broker opt-outs take 7-30 days to process. Some require follow-up. Persistent data (court records, news articles) may require legal removal requests.",
    "url": "https://invisibleexit.com/#faq"
  }
];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') return res.status(200).end();
  
  const query = req.method === 'POST' 
    ? (req.body?.query || '').toLowerCase()
    : (req.query.query || '').toLowerCase();
  
  // Search FAQs
  const matches = query 
    ? content.filter(c => 
        c.name.toLowerCase().includes(query) || 
        c.acceptedAnswer.toLowerCase().includes(query)
      )
    : content;
  
  return res.json({
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    'name': 'InvisibleExit Knowledge Base',
    'description': 'Digital privacy tools to disappear from the internet. Remove personal data from people-search sites, delete online accounts, and protect your identity.',
    'numberOfItems': matches.length,
    'itemListElement': matches
  });
}
